#!/usr/bin/env bash
# script to configure subdomains and display information about them.

get_record_info() {
  local domain="$1"
  local subdomain="$2"

  dig_output=$(dig "$subdomain.$domain" | grep -A1 "ANSWER SECTION:")
  record_type=$(echo "$dig_output" | awk 'NR == 2 {print $4}')
  destination=$(echo "$dig_output" | awk 'NR == 2 {print $5}')

  echo The subdomain "$subdomain" is a "$record_type" record and points to "$destination"
}

if ["$#" -eq 1]; then
  domain="$1"
  for sub in www lb-01 web-01 web-02; do
    get_record_info "$domain"  "$sub"
elif ["$#" -eq 2]; then
  domain=$1
  subdomain=$2
  get_record_info "$domain" "$sub"
fi
